---
parameters:
        #IL_params
        mode: vanilla
        downsample_length: -1
        
        #Network_params
        name: novice
        obs_dim: 2
        action_dim: 1
        policy_hidden_sizes: [64,64,32,32]
        learning_rate: 1e-3
        regularization: 1e-5
        batch_size: 16
        dropout_prob: 0.
        verbose: True
        validation_ratio: 0.1
        max_epochs: 50
        
        # DAgger_params
        beta0: 1.0
        beta_decay: 0.7
...
